run6:
	cargo run --manifest-path=./day6/Cargo.toml --release
.PHONY:run6

run7:
	cargo run --manifest-path=./day7/Cargo.toml --release
.PHONY:run7

run11:
	cargo run --manifest-path=./day11/Cargo.toml --release
.PHONY:run11
