run6:
	cargo run --manifest-path=./day6/Cargo.toml --release
.PHONY:run6

run7:
	cargo run --manifest-path=./day7/Cargo.toml --release
.PHONY:run7

run11:
	cargo run --manifest-path=./day11/Cargo.toml --release
.PHONY:run11

run13:
	cargo run --manifest-path=./day13/Cargo.toml --release
.PHONY:run13

run14:
	cargo run --manifest-path=./day14/Cargo.toml --release
.PHONY:run14

run17:
	cargo run --manifest-path=./day17/Cargo.toml --release
.PHONY:run17

run19:
	cargo run --manifest-path=./day19/Cargo.toml --release
.PHONY:run19
