run5:
	cargo run --manifest-path=./day5/Cargo.toml --release
.PHONY:run5

run8:
	cargo run --manifest-path=./day8/Cargo.toml --release
.PHONY:run8

run14:
	cargo run --manifest-path=./day14/Cargo.toml --release
.PHONY:run14

run17:
	cargo run --manifest-path=./day17/Cargo.toml --release
.PHONY:run17
