# TEST

test5:
	cargo test --manifest-path=./day5/Cargo.toml --no-fail-fast
.PHONY:test5

# BENCH

bench5:
	cargo bench --bench benchmark --manifest-path=./day5/Cargo.toml -- --verbose
.PHONY:bench5

# Run

run5:
	cargo run --manifest-path=./day5/Cargo.toml --release
.PHONY:run5