# Bench

bench7:
	cargo bench --bench benchmark --manifest-path=./day7/Cargo.toml -- --verbose
.PHONY:bench7

# Run
run11:
	cargo run --manifest-path=./day11/Cargo.toml --release
.PHONY:run11

run15:
	cargo run --manifest-path=./day15/Cargo.toml --release
.PHONY:run15

run17:
	cargo run --manifest-path=./day17/Cargo.toml --release
.PHONY:run17

run18:
	cargo run --manifest-path=./day18/Cargo.toml --release
.PHONY:run18

run19:
	cargo run --manifest-path=./day19/Cargo.toml --release
.PHONY:run19

run20:
	cargo run --manifest-path=./day20/Cargo.toml --release
.PHONY:run20

# Test
test12:
	cargo test --manifest-path=./day12/Cargo.toml --no-fail-fast --lib --bins --tests --release
.PHONY:test12