# Bench

bench7:
	cargo bench --bench benchmark --manifest-path=./day7/Cargo.toml -- --verbose
.PHONY:bench7

# Run
run11:
	cargo run --manifest-path=./day11/Cargo.toml --release
.PHONY:run11

# Run
run15:
	cargo run --manifest-path=./day15/Cargo.toml --release
.PHONY:run15

# Test
test12:
	cargo test --manifest-path=./day12/Cargo.toml --no-fail-fast --lib --bins --tests --release
.PHONY:test12