run16:
	cargo run --manifest-path=./day16/Cargo.toml --release
.PHONY:run16

run17:
	cargo run --manifest-path=./day17/Cargo.toml --release
.PHONY:run17

run18:
	cargo run --manifest-path=./day18/Cargo.toml --release
.PHONY:run18
